### ISSUE TITLE
Error using group_by_week on date field with MySQL

### ISSUE THREAD

**Issue by steakchaser** [ankane/groupdate#170]
Running into an error using `group_by_week(:my_date, time_zone: false).count` on a `date` field with MySQL.  Works fine on a `datetime` field.

**Version info:**
- groupdate 3.2.0
- mysql2 0.3.19
- rails 4.2.8

**Error:**
```
irb(main):001:0> MyModel.group_by_week(:my_date, time_zone: false).count
     (795.8ms)  SELECT COUNT(*) AS count_all, CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(my_date, INTERVAL ((1 + WEEKDAY(CONVERT_TZ(my_date, '+00:00', 'Etc/UTC') - INTERVAL 0 second)) % 7) DAY) - INTERVAL 0 second, '+00:00', 'Etc/UTC'), '%Y-%m-%d 00:00:00') + INTERVAL 0 second, 'Etc/UTC', '+00:00') AS week FROM `my_models` WHERE (my_date IS NOT NULL) GROUP BY CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(my_date, INTERVAL ((1 + WEEKDAY(CONVERT_TZ(my_date, '+00:00', 'Etc/UTC') - INTERVAL 0 second)) % 7) DAY) - INTERVAL 0 second, '+00:00', 'Etc/UTC'), '%Y-%m-%d 00:00:00') + INTERVAL 0 second, 'Etc/UTC', '+00:00')
  Groupdate::Error: Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/groupdate-3.2.0/lib/groupdate/magic.rb:186:in `perform'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/groupdate-3.2.0/lib/groupdate/series.rb:14:in `method_missing'
  	from (irb):1
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
  	from /my-project/bin/rails:11:in `<top (required)>'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
  	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
  	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  	from -e:1:in `<main>'
```

**Error using debug_time_zone_support branch** `gem 'groupdate', github: 'ankane/groupdate', branch: 'debug_time_zone_support'`:
```
irb(main):001:0> MyModel.group_by_week(:my_date, time_zone: false).count
   (827.6ms)  SELECT COUNT(*) AS count_all, CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(my_date, INTERVAL ((1 + WEEKDAY(CONVERT_TZ(my_date, '+00:00', 'Etc/UTC') - INTERVAL 0 second)) % 7) DAY) - INTERVAL 0 second, '+00:00', 'Etc/UTC'), '%Y-%m-%d 00:00:00') + INTERVAL 0 second, 'Etc/UTC', '+00:00') AS week FROM `my_models` WHERE (my_date IS NOT NULL) GROUP BY CONVERT_TZ(DATE_FORMAT(CONVERT_TZ(DATE_SUB(my_date, INTERVAL ((1 + WEEKDAY(CONVERT_TZ(my_date, '+00:00', 'Etc/UTC') - INTERVAL 0 second)) % 7) DAY) - INTERVAL 0 second, '+00:00', 'Etc/UTC'), '%Y-%m-%d 00:00:00') + INTERVAL 0 second, 'Etc/UTC', '+00:00')
NoMethodError: undefined method `in_time_zone' for nil:NilClass
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/magic.rb:133:in `block in perform'
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/magic.rb:138:in `block in perform'
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/magic.rb:138:in `each'
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/magic.rb:138:in `map'
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/magic.rb:138:in `perform'
	from /my-project/vendor/bundle/ruby/2.3.0/bundler/gems/groupdate-5a46439a9682/lib/groupdate/series.rb:14:in `method_missing'
	from (irb):1
	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /my-project/bin/rails:11:in `<top (required)>'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /my-project/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**MySQL TZ install test:**
```
mysql> SELECT CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC');
+----------------------------------------+
| CONVERT_TZ(NOW(), '+00:00', 'Etc/UTC') |
+----------------------------------------+
| 2017-05-03 14:33:24                    |
+----------------------------------------+
1 row in set (0.00 sec)
```

**Other:**
```
p Time.now
=> 2017-05-03 14:35:20 -0700
irb(main):018:0> p ENV["TZ"]
=> nil
irb(main):019:0> p ActiveRecord::Base.default_timezone
=> :utc
irb(main):020:0> p ActiveRecord::Base.time_zone_aware_attributes
=> true
```

**Comment by ankane** [comment]
Hey @steakchaser, I'm unable to reproduce. Can you try creating a failing test case for it?
