### ISSUE TITLE
 must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by alkema** [ankane/groupdate#64]
I cannot get the gem to work. I might be doing something wrong, but I can duplicate the issue in a fresh app. 

rails 4.1.6
groupdate 2.3.0
postgres 9.2.4

Example app:
https://github.com/alkema/groupdate-issue

```
irb(main):001:0> User.group_by_day(:created_at).all
  User Load (4.2ms)  SELECT "users".* FROM "users"  WHERE (created_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC'
PG::Error: ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "users".* FROM "users"  WHERE (created_at IS NOT NULL...
               ^
: SELECT "users".* FROM "users"  WHERE (created_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC'
ActiveRecord::StatementInvalid: PG::Error: ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "users".* FROM "users"  WHERE (created_at IS NOT NULL...
               ^
: SELECT "users".* FROM "users"  WHERE (created_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (created_at::timestamptz - INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 hour') AT TIME ZONE 'Etc/UTC'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `async_exec'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `block in exec_no_cache'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `exec_no_cache'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/postgresql_adapter.rb:954:in `select'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/querying.rb:39:in `find_by_sql'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:611:in `exec_queries'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:493:in `load'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:238:in `to_a'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activerecord-4.1.6/lib/active_record/relation.rb:602:in `inspect'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.1.6/lib/rails/commands/console.rb:90:in `start'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.1.6/lib/rails/commands/console.rb:9:in `start'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
    from /Users/jody/apps/foobar/bin/rails:8:in `<top (required)>'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `block in load'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:241:in `load'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/jody/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
```

**Comment by jak1192** [comment]
Has anyone been to do what @ajbraus asked?

**Comment by ajbraus** [comment]
I dropped this gem and just added a js_date cache column and now I use an Angular filter to do the date grouping.

**Comment by ankane** [comment]
@jak1192 you can do:

```ruby
Appointments.where(is_awesome: true).to_a.group_by_day(&:happening_on)
```

**Comment by alex-benoit** [comment]
You can now do
`User.group_by_day(options) { |u| u.created_at }`
This will return and array of records grouped by day
